### ISSUE TITLE
Geckodriver 0.22.0 failing to get the HAR from Firefox

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/browsertime#636]
Upgrading to Geckodriver 0.22.0 introduced:

`
[2018-09-19 10:42:04] ERROR: Could not get the HAR from Firefox JavascriptError: ReferenceError: HAR is not defined
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:514:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:519:13)
    at doSend.then.response (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.executeScript()
    at Driver.schedule (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.executeAsyncScript (/usr/src/app/node_modules/selenium-webdriver/lib/webdriver.js:891:17)
    at SeleniumRunner.runAsyncScript (/usr/src/app/lib/core/seleniumRunner.js:268:26)
    at FirefoxDelegate.onStopIteration (/usr/src/app/lib/firefox/webdriver/firefoxDelegate.js:70:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by soulgalore** [comment]
Upstream: https://github.com/mozilla/geckodriver/issues/1380

**Comment by soulgalore** [comment]
Geckodriver broke the installation of the HAR export trigger. It was fixed in the next release.

**Comment by phongiswindy** [comment]
I am getting this `Object.throwDecodedError` error again in the 6.1.2 version when trying to export the HAR file.

```
Google Chrome 77.0.3865.75 
Mozilla Firefox 69.0
[2019-10-22 10:11:11] INFO: Running tests using Firefox - 1 iteration(s)
[2019-10-22 10:11:14] INFO: Testing url http://www.team.aero iteration 1
[2019-10-22 10:11:23] INFO: Waiting on har-export-trigger to collect the HAR
[2019-10-22 10:14:13] ERROR: Could not get the HAR from Firefox ScriptTimeoutError: Timed out after 170000 ms
    at Object.throwDecodedError (/usr/src/app/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/usr/src/app/node_modules/selenium-webdriver/lib/http.js:486:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-10-22 10:14:14] INFO: http://www.team.aero backEndTime: 1.32s, firstPaint: 2.18s, DOMContentLoaded: 2.23s, Load: 2.51s, rumSpeedIndex: 1682
[2019-10-22 10:14:14] INFO: Wrote data to www.team.aero
```

**Comment by soulgalore** [comment]
Hi @phongiswindy that error is that the JavaScript that collect the HAR file never returns. We use https://github.com/firefox-devtools/har-export-trigger and I guess then there is something on that page that makes the code take forever.  We need to create upstream issue. Could you do that? 

Best
Peter

**Comment by phongiswindy** [comment]
@soulgalore I think this error is still there from the up stream in the latest version 8.1.2. I was trying to get HAR from Firefox for sites like nihb.org, neurowaves.com and get the same error. Hope the up-stream package will be fixed soon.
